# Generated by Django 6.0 on 2025-12-08 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер стола')),
                ('places_count', models.PositiveIntegerField(default=4, verbose_name='Количество мест')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('start_date', models.DateField(verbose_name='Дата заезда')),
                ('end_date', models.DateField(verbose_name='Дата выезда')),
                ('access_code', models.CharField(help_text='Пароль для входа гостя', max_length=10, verbose_name='Код доступа')),
            ],
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_number', models.PositiveIntegerField(verbose_name='Место за столом')),
                ('start_date', models.DateField(verbose_name='С какого числа')),
                ('end_date', models.DateField(verbose_name='По какое число')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='dining.guest', verbose_name='Отдыхающий')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dining.diningtable', verbose_name='Стол')),
            ],
            options={
                'verbose_name': 'Посадка за стол',
                'verbose_name_plural': 'Посадки за столы',
            },
        ),
    ]
