# Generated by Django 6.0 on 2025-12-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0002_guest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.AlterField(
            model_name='guest',
            name='access_code',
            field=models.CharField(help_text='Пароль для входа гостя', max_length=10, unique=True, verbose_name='Код доступа'),
        ),
    ]
