# Generated by Django 6.0 on 2025-12-08 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0003_remove_guest_user_alter_guest_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('is_diet', models.BooleanField(default=False, verbose_name='Диетическое блюдо')),
                ('proteins', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Белки, г')),
                ('fats', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Жиры, г')),
                ('carbs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Углеводы, г')),
                ('kcal', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Ккал')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название меню')),
                ('days_count', models.PositiveSmallIntegerField(default=7, verbose_name='Дней в цикле')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveSmallIntegerField(verbose_name='День цикла (1-7)')),
                ('diet_kind', models.CharField(choices=[('diet', 'Диетическое'), ('regular', 'Обычное')], default='regular', max_length=10, verbose_name='Тип меню')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='dining.menucycle', verbose_name='Меню')),
            ],
            options={
                'unique_together': {('cycle', 'day_index', 'diet_kind')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('snack', 'Полдник'), ('dinner', 'Ужин')], max_length=10, verbose_name='Приём пищи')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Раздел (ЗАКУСКИ, 1-е БЛЮДА и т.п.)')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок в разделе')),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dining.dailymenu', verbose_name='Меню на день')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dining.dish', verbose_name='Блюдо')),
            ],
            options={
                'ordering': ['meal_time', 'order_index', 'id'],
            },
        ),
    ]
