# Generated by Django 6.0 on 2025-12-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0004_dish_menucycle_dailymenu_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='diet_kind',
            field=models.CharField(choices=[('diet', 'Диетическое'), ('regular', 'Обычное')], default='regular', max_length=10, verbose_name='Тип меню (обычное/диетическое)'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('meal_time', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('snack', 'Полдник'), ('dinner', 'Ужин')], max_length=10, verbose_name='Приём пищи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dining.guest', verbose_name='Отдыхающий')),
            ],
            options={
                'unique_together': {('guest', 'date', 'meal_time')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dining.menuitem', verbose_name='Позиция меню')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dining.order', verbose_name='Заказ')),
            ],
        ),
    ]
