# Generated by Django 6.0 on 2025-12-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0005_guest_diet_kind_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='day_index',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели'),
        ),
    ]
