# Generated by Django 6.0 on 2025-12-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0006_alter_dailymenu_day_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['meal_time', 'order_index', '-id']},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order_index',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок в разделе'),
        ),
    ]
