# Generated by Django 6.0 on 2025-12-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0007_alter_menuitem_options_alter_menuitem_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='output',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Выход, г'),
        ),
    ]
