# Generated by Django 6.0 on 2025-12-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0008_dish_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Общее блюдо (выдаётся всем)'),
        ),
    ]
