# Generated by Django 6.0 on 2025-12-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0009_menuitem_is_common'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='diet_kind',
            field=models.CharField(choices=[('P', 'П (пищевод)'), ('B', 'Б (обычное)'), ('BD', 'БД (диабетическое)')], default='B', max_length=10, verbose_name='Вид диеты (П/Б/БД)'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='diet_kind',
            field=models.CharField(choices=[('P', 'П (пищевод)'), ('B', 'Б (обычное)'), ('BD', 'БД (диабетическое)')], default='B', max_length=10, verbose_name='Вид диеты (П/Б/БД)'),
        ),
    ]
