# Generated by Django 6.0 on 2025-12-12 11:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0010_alter_dailymenu_diet_kind_alter_guest_diet_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRotationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateField(default=datetime.date(2025, 12, 8), verbose_name='Базовая дата начала Меню №1 (понедельник)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forced_cycle', models.ForeignKey(blank=True, help_text='Если не задано — используется автоматическое чередование.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dining.menucycle', verbose_name='Принудительно использовать меню')),
            ],
        ),
    ]
