# Generated by Django 6.0 on 2025-12-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0011_menurotationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='breakfast_allowed',
            field=models.BooleanField(default=True, help_text='Разрешить выбор завтрака', verbose_name='Завтрак'),
        ),
        migrations.AddField(
            model_name='guest',
            name='dinner_allowed',
            field=models.BooleanField(default=True, help_text='Разрешить выбор ужина', verbose_name='Ужин'),
        ),
        migrations.AddField(
            model_name='guest',
            name='lunch_allowed',
            field=models.BooleanField(default=True, help_text='Разрешить выбор обеда', verbose_name='Обед'),
        ),
        migrations.AddField(
            model_name='guest',
            name='snack_allowed',
            field=models.BooleanField(default=True, help_text='Разрешить выбор полдника', verbose_name='Полдник'),
        ),
    ]
