# Generated by Django 6.0 on 2025-12-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0012_guest_breakfast_allowed_guest_dinner_allowed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymenu',
            options={'verbose_name': 'Меню на день', 'verbose_name_plural': 'Меню по дням'},
        ),
        migrations.AlterModelOptions(
            name='diningtable',
            options={'verbose_name': 'Стол', 'verbose_name_plural': 'Столы'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Отдыхающий', 'verbose_name_plural': 'Отдыхающие'},
        ),
        migrations.AlterModelOptions(
            name='menucycle',
            options={'verbose_name': 'Цикл меню', 'verbose_name_plural': 'Циклы меню'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['meal_time', 'order_index', '-id'], 'verbose_name': 'Позиция меню', 'verbose_name_plural': 'Позиции меню'},
        ),
        migrations.AlterModelOptions(
            name='menurotationconfig',
            options={'verbose_name': 'Настройка чередования меню', 'verbose_name_plural': 'Настройки чередования меню'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
        migrations.AddField(
            model_name='guest',
            name='departure_dinner',
            field=models.BooleanField(default=False, verbose_name='Ужин в день выезда (платный)'),
        ),
        migrations.AddField(
            model_name='guest',
            name='departure_lunch',
            field=models.BooleanField(default=False, verbose_name='Обед в день выезда (платный)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_time',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], max_length=10, verbose_name='Приём пищи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal_time',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], max_length=10, verbose_name='Приём пищи'),
        ),
    ]
