# Generated by Django 6.0 on 2025-12-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0013_alter_dailymenu_options_alter_diningtable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='departure_dinner',
            field=models.BooleanField(default=False, help_text='Разрешить ужин в последний день пребывания', verbose_name='Ужин в день выезда (платный)'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='departure_lunch',
            field=models.BooleanField(default=False, help_text='Разрешить обед в последний день пребывания', verbose_name='Обед в день выезда (платный)'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='snack_allowed',
            field=models.BooleanField(default=False, help_text='Разрешить выбор полдника', verbose_name='Полдник'),
        ),
    ]
