# Generated by Django 6.0 on 2025-12-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0014_alter_guest_departure_dinner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='short_name',
            field=models.CharField(blank=True, help_text='Если заполнено, официанты и кухня будут видеть это название (сокращенное). Если пусто — полное.', max_length=100, verbose_name='Название для кухни/официантов'),
        ),
    ]
